# Generated by Django 5.1.7 on 2025-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0003_rename_product_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
